structure:
  - .github/workflows/test.yaml:
      content: |
        name: test-perl

        on:
          push:
            branches: [ master ]
          pull_request:
            branches: [ master ]

        jobs:
          test:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@{{@ "actions/checkout" | latest_release @}}

              - name: Set up Perl
                uses: shogo82148/actions-setup-perl@{{@ "shogo82148/actions-setup-perl" | latest_release @}}
                with:
                  perl-version: '5.36'

              - name: Install dependencies
                run: |
                  sudo apt-get update
                  sudo apt-get install -y librrds-perl \
                  libjson-perl \
                  libhtml-parser-perl \
                  libcgi-pm-perl \
                  libipc-run-perl

              - name: Run tests
                run: |
                  export PERL5LIB=$PERL5LIB:/usr/share/perl5
                  prove -lrv t > tap.out
                  cat tap.out

              - name: Convert TAP to Markdown inline
                run: |
                  python3 - <<'EOF'
                  import re
                  # Read the TAP output from file
                  with open('tap.out') as f:
                      lines = f.readlines()

                  total = 0
                  passed = 0
                  failed = 0
                  details = []

                  for line in lines:
                      line = line.strip()
                      if re.match(r'^ok\b', line):
                          passed += 1
                          total += 1
                          details.append(f"- ✅ {line}")
                      elif re.match(r'^not ok\b', line):
                          failed += 1
                          total += 1
                          details.append(f"- ❌ {line}")

                  # Build the Markdown report
                  print("# Test Results")
                  print("")
                  print(f"**Total tests:** {total}")
                  print(f"**Passed:** {passed}")
                  print(f"**Failed:** {failed}")
                  print("")
                  print("## Test Details")
                  print("")
                  for detail in details:
                      print(detail)
                  EOF > results.md

              - name: Show Markdown Test Results as step summary
                run: cat results.md >> $GITHUB_STEP_SUMMARY

              - name: Upload Markdown Test Results
                uses: actions/upload-artifact@v4
                with:
                  name: test-results-markdown
                  path: results.md

              - name: Upload TAP Test Results
                uses: actions/upload-artifact@v4
                with:
                  name: test-results-tap
                  path: tap.out

folders:
  - ./:
      struct:
        - github/workflows/pre-commit
        - github/workflows/release-drafter
        - github/workflows/run-struct
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
