"""Graph definitions for collectd-web.

Ported from cgi-bin/graphdefs.cgi.

Each key is a collectd plugin/type name.
Each value is a list of RRD graph arguments.
The placeholder {file} is replaced at render time with the actual RRD file path.
"""
from __future__ import annotations

GRAPH_DEFS: dict[str, list[str]] = {

        "apache_bytes": ['DEF:min_raw={file}:count:MIN',
        'DEF:avg_raw={file}:count:AVERAGE',
        'DEF:max_raw={file}:count:MAX',
        'CDEF:min=min_raw,8,*',
        'CDEF:avg=avg_raw,8,*',
        'CDEF:max=max_raw,8,*',
        'CDEF:mytime=avg_raw,TIME,TIME,IF',
        'CDEF:sample_len_raw=mytime,PREV(mytime),-',
        'CDEF:sample_len=sample_len_raw,UN,0,sample_len_raw,IF',
        'CDEF:avg_sample=avg_raw,UN,0,avg_raw,IF,sample_len,*',
        'CDEF:avg_sum=PREV,UN,0,PREV,IF,avg_sample,+',
        "AREA:avg#B7B7F7",
        "LINE1:avg#0000FF:Bit/s",
        'GPRINT:min:MIN:%5.1lf%s Min,',
        'GPRINT:avg:AVERAGE:%5.1lf%s Avg,',
        'GPRINT:max:MAX:%5.1lf%s Max,',
        'GPRINT:avg:LAST:%5.1lf%s Last',
        'GPRINT:avg_sum:LAST:(ca. %5.1lf%sB Total)\\l'
        ],
        "apache_requests": ['DEF:min={file}:count:MIN',
        'DEF:avg={file}:count:AVERAGE',
        'DEF:max={file}:count:MAX',
        "AREA:max#B7B7F7",
        "AREA:min#FFFFFF",
        "LINE1:avg#0000FF:Requests/s",
        'GPRINT:min:MIN:%6.2lf Min,',
        'GPRINT:avg:AVERAGE:%6.2lf Avg,',
        'GPRINT:max:MAX:%6.2lf Max,',
        'GPRINT:avg:LAST:%6.2lf Last'
        ],
        "apache_scoreboard": ['DEF:min={file}:count:MIN',
        'DEF:avg={file}:count:AVERAGE',
        'DEF:max={file}:count:MAX',
        "AREA:max#B7B7F7",
        "AREA:min#FFFFFF",
        "LINE1:avg#0000FF:Processes",
        'GPRINT:min:MIN:%6.2lf Min,',
        'GPRINT:avg:AVERAGE:%6.2lf Avg,',
        'GPRINT:max:MAX:%6.2lf Max,',
        'GPRINT:avg:LAST:%6.2lf Last'
        ],
        "bitrate": ['-v', 'Bits/s',
        'DEF:avg={file}:value:AVERAGE',
        'DEF:min={file}:value:MIN',
        'DEF:max={file}:value:MAX',
        "AREA:max#B7B7F7",
        "AREA:min#FFFFFF",
        "LINE1:avg#0000FF:Bits/s",
        'GPRINT:min:MIN:%5.1lf%s Min,',
        'GPRINT:avg:AVERAGE:%5.1lf%s Average,',
        'GPRINT:max:MAX:%5.1lf%s Max,',
        'GPRINT:avg:LAST:%5.1lf%s Last\\l'
        ],
        "charge": ['-v', 'Ah',
        'DEF:avg={file}:value:AVERAGE',
        'DEF:min={file}:value:MIN',
        'DEF:max={file}:value:MAX',
        "AREA:max#B7B7F7",
        "AREA:min#FFFFFF",
        "LINE1:avg#0000FF:Charge",
        'GPRINT:min:MIN:%5.1lf%sAh Min,',
        'GPRINT:avg:AVERAGE:%5.1lf%sAh Avg,',
        'GPRINT:max:MAX:%5.1lf%sAh Max,',
        'GPRINT:avg:LAST:%5.1lf%sAh Last\\l'
        ],
        "contextswitch": ['-v', 'Switches/s',
        'DEF:min={file}:contextswitches:AVERAGE',
        'DEF:min={file}:contextswitches:MIN',
        'DEF:max={file}:contextswitches:MAX',
        "AREA:max#B7B7F7",
        "AREA:min#FFFFFF",
        "LINE1:avg#0000FF:Switches/s",
        'GPRINT:min:MIN:%4.1lf ms Min,',
        'GPRINT:avg:AVERAGE:%4.1lf ms Avg,',
        'GPRINT:max:MAX:%4.1lf ms Max,',
        'GPRINT:avg:LAST:%4.1lf ms Last'
        ],
        "cpu": ['-v', 'CPU load',
        'DEF:avg={file}:value:AVERAGE',
        'DEF:min={file}:value:MIN',
        'DEF:max={file}:value:MAX',
        "AREA:max#B7B7F7",
        "AREA:min#FFFFFF",
        "LINE1:avg#0000FF:CPU",
        'GPRINT:min:MIN:%5.1lf%% Min,',
        'GPRINT:avg:AVERAGE:%5.1lf%% Avg,',
        'GPRINT:max:MAX:%5.1lf%% Max,',
        'GPRINT:avg:LAST:%5.1lf%% Last\\l'
        ],
        "current": ['-v', 'Ampere',
        'DEF:avg={file}:value:AVERAGE',
        'DEF:min={file}:value:MIN',
        'DEF:max={file}:value:MAX',
        "AREA:max#B7B7F7",
        "AREA:min#FFFFFF",
        "LINE1:avg#0000FF:Current",
        'GPRINT:min:MIN:%5.2lf A Min,',
        'GPRINT:avg:AVERAGE:%5.2lf A Avg,',
        'GPRINT:max:MAX:%5.2lf A Max,',
        'GPRINT:avg:LAST:%5.2lf A Last\\l'
        ],
        "df": ['-v', 'Percent', '-l', '0',
        'DEF:avg={file}:value:AVERAGE',
        'DEF:min={file}:value:MIN',
        'DEF:max={file}:value:MAX',
        "AREA:max#B7B7F7",
        "AREA:min#FFFFFF",
        "LINE1:avg#0000FF:Percent",
        'GPRINT:min:MIN:%4.1lf%% Min,',
        'GPRINT:avg:AVERAGE:%4.1lf%% Avg,',
        'GPRINT:max:MAX:%4.1lf%% Max,',
        'GPRINT:avg:LAST:%4.1lf%% Last\\l'
        ],
        "disk": [
        'DEF:rmin={file}:read:MIN',
        'DEF:ravg={file}:read:AVERAGE',
        'DEF:rmax={file}:read:MAX',
        'DEF:wmin={file}:write:MIN',
        'DEF:wavg={file}:write:AVERAGE',
        'DEF:wmax={file}:write:MAX',
        'CDEF:overlap=ravg,wavg,GT,wavg,ravg,IF',
        'CDEF:mytime=ravg,TIME,TIME,IF',
        'CDEF:sample_len_raw=mytime,PREV(mytime),-',
        'CDEF:sample_len=sample_len_raw,UN,0,sample_len_raw,IF',
        'CDEF:ravg_sample=ravg,UN,0,ravg,IF,sample_len,*',
        'CDEF:ravg_sum=PREV,UN,0,PREV,IF,ravg_sample,+',
        'CDEF:wavg_sample=wavg,UN,0,wavg,IF,sample_len,*',
        'CDEF:wavg_sum=PREV,UN,0,PREV,IF,wavg_sample,+',
        "AREA:ravg#B7EFB7",
        "AREA:wavg#B7B7F7",
        "AREA:overlap#DFB7F7",
        "LINE1:ravg#00E000:Read",
        'GPRINT:rmin:MIN:%5.1lf%s Min,',
        'GPRINT:ravg:AVERAGE:%5.1lf%s Avg,',
        'GPRINT:rmax:MAX:%5.1lf%s Max,',
        'GPRINT:ravg:LAST:%5.1lf%s Last\\l',
        "LINE1:wavg#0000FF:Write",
        'GPRINT:wmin:MIN:%5.1lf%s Min,',
        'GPRINT:wavg:AVERAGE:%5.1lf%s Avg,',
        'GPRINT:wmax:MAX:%5.1lf%s Max,',
        'GPRINT:wavg:LAST:%5.1lf%s Last\\l',
        'GPRINT:ravg_sum:LAST:(ca. %5.1lf%sB Read Total)\\l',
        'GPRINT:wavg_sum:LAST:(ca. %5.1lf%sB Write Total)\\l'
        ],
}
