name: debian-package

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build Debian package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev debhelper devscripts build-essential

      - name: Build Debian package
        run: |
          dpkg-buildpackage -us -uc
          mv ../collectd-web_* ./debian/out

      - name: Upload .deb file to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./debian/out/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
